.

diff --git a/ci/vim-tests.yml b/ci/vim-tests.yml
--- a/ci/vim-tests.yml
+++ b/ci/vim-tests.yml
@@ -22,6 +22,20 @@ steps:
     displayName: Compile Padre CLI
 
   - bash: |
+      success=0
+      fail=0
+      for i in {1..5}; do
+          vim '+Vader! test/unit/test_job.vader'
+          if [[ $? == 0 ]]; then
+              success=$((${success} + 1))
+          else
+              fail=$((${success} + 1))
+          fi
+      done
+      echo "Ran test 5 times and got ${success} successes and ${fail} failures"
+    displayName: Check frequency of passing/failing test
+
+  - bash: |
       vim '+Vader! test/unit/*.vader'
     displayName: Run VIM unit tests
 
